version: '3.8'

services:
  clicknbuy-db:
    image: mysql:8
    container_name: clicknbuy-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clicknbuy
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Kolkata
    ports:
      - "3306:3306"
    volumes:
      - clicknbuy-data:/var/lib/mysql
    networks:
      - app-network

  springapp:
    image: geethar27/springapp:latest
    container_name: springapp
    depends_on:
      - clicknbuy-db
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://clicknbuy-db:3306/clicknbuy?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      
      EMAIL_USERNAME: geethar272003@gmail.com
      EMAIL_PASSWORD: ozopfngqzxumganao
      CLOUDINARY_URL: cloudinary://289133591992525:7DCImx3QCwjki1LTbEWDz4mlA0s@djkyoabl5

      TZ: Asia/Kolkata

networks:
  app-network:
    driver: bridge

volumes:
  clicknbuy-data:
